
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 30 10:38:17 CST 2016
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int senten_fn = 31;
  public static final int ope_and = 14;
  public static final int Divide = 13;
  public static final int ope_neg = 24;
  public static final int ope_diferente = 17;
  public static final int Suma = 11;
  public static final int coma = 30;
  public static final int Multipl = 10;
  public static final int senten_mientras = 23;
  public static final int parent_derec = 25;
  public static final int corch_izq = 22;
  public static final int senten_para = 27;
  public static final int ope_mayor = 29;
  public static final int ID = 2;
  public static final int senten_si = 20;
  public static final int ope_comp = 16;
  public static final int EOF = 0;
  public static final int let = 6;
  public static final int Resta = 12;
  public static final int ope_or = 15;
  public static final int LINE_COMMENT = 5;
  public static final int error = 1;
  public static final int corch_derec = 21;
  public static final int FIN_COMMENT = 4;
  public static final int parent_izq = 26;
  public static final int Asig = 7;
  public static final int ope_menor = 28;
  public static final int ope_menor_igual = 18;
  public static final int punto_coma = 8;
  public static final int INI_COMMENT = 3;
  public static final int ope_mayor_igual = 19;
  public static final int Number = 9;
}

